### ISSUE TITLE
Error on Arch Linux

### ISSUE THREAD

**Issue by entodoays** [pulb/mailnag#101]
I'm getting this error when launching mailnag.

** (mailnag:4033): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
INFO (2015-09-10 07:21:59): Successfully enabled plugin 'dbusplugin'.
INFO (2015-09-10 07:21:59): Successfully enabled plugin 'libnotifyplugin'.
INFO (2015-09-10 07:21:59): Successfully enabled plugin 'soundplugin'.
INFO (2015-09-10 07:21:59): Successfully enabled plugin 'goaplugin'.
ERROR (2015-09-10 07:21:59): Caught an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Mailnag/common/utils.py", line 82, in try_call
    return f()
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mailnagdaemon.py", line 176, in <lambda>
    try_call( lambda: f(self._accounts) )
  File "/usr/lib/python2.7/site-packages/Mailnag/plugins/goaplugin.py", line 67, in accounts_loaded_hook
    ssl = mail.props.imap_use_ssl, imap = True, idle = True, folder = '')
TypeError: __init__() got an unexpected keyword argument 'folder'
INFO (2015-09-10 07:21:59): Checking 0 email account(s).

**Comment by Ikagen** [comment]
As for the error, try to do the following as a root:
- Open the file */usr/lib/python2.7/site-packages/Mailnag/plugins/goaplugin.py*
- Find line 67: 
```python
ssl = mail.props.imap_use_ssl, imap = True, idle = True, folder = '') 
```
- Change it to: 
```python
ssl = mail.props.imap_use_ssl, imap = True, idle = True, folders = '')
```
- Run this command in terminal (as a root): 
```bash 
python -m compileall /usr/lib/python2.7/site-packages/Mailnag/plugins/
```
Now you can launch *mailnag* and check if the error is gone.

**Comment by entodoays** [comment]
I tried this modification and got:
```
** (mailnag:4755): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
INFO (2015-09-11 12:05:37): Successfully enabled plugin 'dbusplugin'.
INFO (2015-09-11 12:05:37): Successfully enabled plugin 'libnotifyplugin'.
INFO (2015-09-11 12:05:37): Successfully enabled plugin 'soundplugin'.
INFO (2015-09-11 12:05:37): Successfully enabled plugin 'goaplugin'.
ERROR (2015-09-11 12:05:37): Caught an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Mailnag/common/utils.py", line 82, in try_call
    return f()
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mailnagdaemon.py", line 176, in <lambda>
    try_call( lambda: f(self._accounts) )
  File "/usr/lib/python2.7/site-packages/Mailnag/plugins/goaplugin.py", line 67, in accounts_loaded_hook
    ssl = mail.props.imap_use_ssl, imap = True, idle = True, folders = '')
TypeError: __init__() got an unexpected keyword argument 'folder'
INFO (2015-09-11 12:05:37): Checking 0 email account(s).
```

**Comment by Ikagen** [comment]
Looks like the last command didn't succeed. Try to remove file */usr/lib/python2.7/site-packages/Mailnag/plugins/goaplugin.pyc* first.

**Comment by entodoays** [comment]
Would that disable the goa plugin?

**Comment by Ikagen** [comment]
No. You have changed the source code (*goaplugin.py*), because there was a typo. But the changes were not applied to mailnag, because *goaplugin.pyc* (compiled *goaplugin.py*) was not updated. You have to recompile *goaplugin.py*, which can be done using the command I told you. But for some reason it didn't work (are you sure you ran it as a root?), so I suggest you to remove the old *goaplugin.pyc* (you can just move it somewhere as well) and try to compile it again. 

It might actually work even without compiling, because python doesn't really need it (it just reduces the load time), just remove the *goaplugin.pyc*.

**Comment by entodoays** [comment]
I did what you suggested (deleting the goaplugin.pyc and recompiling) and now it is working. Thanks.

**Comment by pulb** [comment]
Fixed. @entodoays thanks for reporting and @Ikagen thanks for providing a fix! :)
