### ISSUE TITLE
[GNOME 3.18] Fix Gtk warnings in mailnag-config

### ISSUE THREAD

**Issue by pulb** [pulb/mailnag#105]
Starting mailnag-config in a terminal reveals some Gtk warnings in GNOME 3.18

**Comment by kyleamadio** [comment]
Yes - these

/usr/bin/mailnag-config:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python2.7/dist-packages/Mailnag/common/credentialstore.py:38: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
/usr/lib/python2.7/dist-packages/Mailnag/plugins/goaplugin.py:24: PyGIWarning: Goa was imported without specifying a version first. Use gi.require_version('Goa', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Goa
/usr/lib/python2.7/dist-packages/Mailnag/plugins/libnotifyplugin.py:27: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify, Gio, Gtk
/usr/lib/python2.7/dist-packages/Mailnag/plugins/soundplugin.py:26: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
