### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by kparal** [pulb/mailnag#111]
Hi, I was wondering whether you're interested in occasionally receiving some small thank-you money for developing mailnag? If you do, what about putting a PayPal link or a Flattr button or something similar into readme?

**Comment by pulb** [comment]
Hi, I thought about that before and since you filed an official bugreport for it, I had no choice but to fix it by adding a paypal donate button. :grin:

**Comment by pulb** [comment]
Many thanks! :smile:

**Comment by kparal** [comment]
No, thank you. Hopefully others will use that button as well :-)
