### ISSUE TITLE
Mailnag 1.1.0.stopped working with Gmail due to IMAP issues

### ISSUE THREAD

**Issue by hias1234** [pulb/mailnag#112]
IMAP is enabled in my Gmail accounts, though this is what it says:

$ mailnag
INFO (2015-12-30 10:48:41): Successfully enabled plugin 'dbusplugin'.
INFO (2015-12-30 10:48:41): Successfully enabled plugin 'unityplugin'.
INFO (2015-12-30 10:48:41): Successfully enabled plugin 'libnotifyplugin'.
INFO (2015-12-30 10:48:41): Successfully enabled plugin 'soundplugin'.
INFO (2015-12-30 10:48:41): Successfully enabled plugin 'userscriptplugin'.
INFO (2015-12-30 10:48:41): Checking 2 email account(s).
ERROR (2015-12-30 10:48:42): Cannot connect to IMAP account 'imap.gmail.com'.
ERROR (2015-12-30 10:48:43): Cannot connect to IMAP account 'imap.gmail.com'.
ERROR (2015-12-30 10:48:44): Cannot connect to IMAP account 'imap.gmail.com'.
ERROR (2015-12-30 10:48:44): Error: Failed to create an idler thread for account 'hias1234 (Gmail)'
ERROR (2015-12-30 10:48:44): Cannot connect to IMAP account 'imap.gmail.com'.
ERROR (2015-12-30 10:48:45): Error: Failed to create an idler thread for account 'mf@prima-marktforschung.de (Gmail)'

System is Ubuntu 14.04 with unity.

**Comment by pulb** [comment]
Can you post your mailnag.cfg?

**Comment by hias1234** [comment]
here it comes:
__________
[spamfilterplugin]
filter_text = newsletter, viagra

[core]
imap_idle_timeout = 10
enabled_plugins = dbusplugin, userscriptplugin, soundplugin, libnotifyplugin, unityplugin
poll_interval = 1
credentialstore = auto
connectivity_test = auto
autostart = 1

[unityplugin]
max_visible_mails = 10

[soundplugin]
soundfile = mailnag.ogg

[libnotifyplugin]
notification_mode = 1
max_visible_mails = 10

[account2]
enabled = 1
name = mf@prima-marktforschung.de (Gmail)
user = mf@prima-marktforschung.de
password = 
server = imap.gmail.com
port = 993
ssl = 1
imap = 1
idle = 1
folder = 

[account1]
enabled = 1
name = hias1234 (Gmail)
user = hias1234
password = 
server = imap.gmail.com
port = 993
ssl = 1
imap = 1
idle = 1
folder = 

[userscriptplugin]
script_file = /home/hias/email

____________

Regards
Matthias

**Comment by pulb** [comment]
Are you sure those user names ever worked? :smile:

**Comment by hias1234** [comment]
At least account 1 worked before. Account 2 has been added just a few days ago (probably that is the problem?). I do not recall if account 2 ever worked, maybe not.

**Comment by pulb** [comment]
Please try to use the email address for the user name. Maybe you're using 2-step verification in gmail? If so, you have to generate an application-specific password and use it in the config above, instead of your real password. See https://accounts.google.com/b/0/IssuedAuthSubTokens

**Comment by hias1234** [comment]
No 2 way authentication. :-<

editing mailnag.cfg and changing "User = hias1234" into "User = hias1234@gmail.com" plus inserting the password new into mailnag-config worked for this account. 

However, the second account still does not work. Maybe the application does not support a "google for work" email adress (mf@prima-marktforschung.de) which does not end on @gmail?

**Comment by pulb** [comment]
If this google for work email address is working with www.gmail.com, then it should work with Mailnag, too. Do you have an alternative, official "@gmail" address you can use for the problematic account?
(oh and please use mailnag-config whenever possible instead of editing the cfg direclty to prevent mistakes)

**Comment by pulb** [comment]
Maybe you also have to use a different mailserver for google-for-work? If so you have to choose "Other (IMAP)" when adding the account in mailnag-config.

**Comment by hias1234** [comment]
Yes, "google for work" works with www.gmail.com. There is no @gmail adress for the "google for work" account (mf@prima-marktforschung.de is no alias but the original adress which is why I've choosen the payable google for work account. It prevents "send on behalf of ..." messages in emails).

Choosing "other IMAP" does not help  as it stays still the same old image server namely  "imap.gmail.com, Port: 993" which is correct. 
However, can it be that mailnag needs "activate less secure apps" setting in gmail? I cannot find this setting in the "google for work" setting site for now, but I might contact the google support on that if you think that is the reason why mailnag fails here.

**Comment by pulb** [comment]
Maybe [this](https://support.google.com/a/answer/105694?hl=de) is of help.

**Comment by hias1234** [comment]
basically that describes where the setting is: https://support.google.com/a/answer/6260879?hl=de

Google for work setting site seems to be down right now. I give you a feedback once I've changed the security setting. 

Can you confirm that mailnag transfers the password without additional encryption and needs "less secure apps" setting in Gmail?

**Comment by pulb** [comment]
Well I don't know how google defines "less secure". Mailag uses imaplib2 which is using SSL encrypted connections.

**Comment by pulb** [comment]
https://support.google.com/a/answer/105694?hl=de does not help either?

**Comment by hias1234** [comment]
no that is not for "google for work" but for a normal account. 
This is the correct help for "google for work"  https://support.google.com/a/answer/6260879?hl=de

I succeeded to switch the account to "enforce less secure apps". Nailnag immediatedly works. Issue solved. Thank you.

To sum it up: mailangs needs Google to let "less secure apps" access the account. "Google for work" accounts may be set up to deny "less secure apps" the access unless the admin chooses to change that.

**Comment by pulb** [comment]
Ok, great to hear you got it solved. Will be of help next time someone else has the same issue :-)

**Comment by althaser** [comment]
you can have the 2-step verification enabled if you use https://security.google.com/settings/security/apppasswords to add mailnag application and later use in mailnag-config the generated password instead of google password. :-)
