### ISSUE TITLE
Ubuntu Gnome 16.04  Panel indicator does not always appear.

### ISSUE THREAD

**Issue by kyleamadio** [pulb/mailnag#118]
On Gnome Shell 3.18 Ubuntu Gnome - its a bit buggy - the panel indicator does not always appear and the app sometimes crashes.

Version is 1.2

Have to manually switch the Shell Extension on.

Seems to disconnect from the Gmail Accounts to.

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/Mailnag/daemon/idlers.py", line 103, in _idle
    self._reconnect()
  File "/usr/lib/python2.7/dist-packages/Mailnag/daemon/idlers.py", line 142, in _reconnect
    self._select(self._conn, self._account)
  File "/usr/lib/python2.7/dist-packages/Mailnag/daemon/idlers.py", line 147, in _select
    conn.select(acount.folders[0])
NameError: global name 'acount' is not defined

INFO (2016-03-29 21:07:57): Idler thread for account 'l' has been disconnected
INFO (2016-03-29 21:07:57): Trying to reconnect Idler thread for account ''.
ERROR (2016-03-29 21:08:02): Failed to reconnect Idler thread for account '' ([AUTHENTICATIONFAILED] Invalid credentials (Failure)).
INFO (2016-03-29 21:08:02): Trying to reconnect Idler thread for account '' in 5 minutes
INFO (2016-03-29 21:13:03): Trying to reconnect Idler thread for account ''.
ERROR (2016-03-29 21:13:05): Failed to reconnect Idler thread for account '' ([AUTHENTICATIONFAILED] Invalid credentials (Failure)).
INFO (2016-03-29 21:13:05): Trying to reconnect Idler thread for account ' in 5 minutes
INFO (2016-03-29 21:18:06): Trying to reconnect Idler thread for account '.'.
ERROR (2016-03-29 21:18:12): Failed to reconnect Idler thread for account '' ([AUTHENTICATIONFAILED] Invalid credentials (Failure)).
INFO (2016-03-29 21:18:12): Trying to reconnect Idler thread for account '' in 5 minutes
INFO (2016-03-29 21:23:12): Trying to reconnect Idler thread for account ''.
ERROR (2016-03-29 21:23:15): Failed to reconnect Idler thread for account '' ([AUTHENTICATIONFAILED] Invalid credentials (Failure)).
INFO (2016-03-29 21:23:15): Trying to reconnect Idler thread for account '' in 5 minutes

**Comment by pulb** [comment]
Many thanks for your bugreport - it seems you spoted a real bug :)
Please try the following:
`cd /usr/lib/python2.7/dist-packages/Mailnag`
`sudo rm idlers.pyc`
`sudo gedit idlers.py` and replace _conn.select(acount.folders[0])_ at line 147 by _conn.select(account.folders[0])_
Save the file and restart mailnag.

Your log also show some "Invalid credentials" errors. This may be related to the bug in idlers.py but it's also possible you entered a wrong username/password.
