### ISSUE TITLE
Run mailnag outside Gnome

### ISSUE THREAD

**Issue by mehturt** [pulb/mailnag#126]
Is it possible to run mailnag outside Gnome? I'm looking for IMAP mail notification tool that either displays notification of some kind, or simply runs my script.
I'm on Debian jessie, trying mailnag with my X/ratpoison. I am currently stuck on issue similar to issue 79, mailnag-config fails every time to unlock default keyring.
I run seahorse and created default password with both my login (ssh) password and blank password, but mailnag-config still does not work.

**Comment by pulb** [comment]
Thanks for your bugreport.
Mailnag does not depend on GNOME and the keyring dependency is optional. If you don't want to use GNOME keyring set `credentialstore = auto` to `credentialstore = none` in ~/.config/mailnag.config.

**Comment by pulb** [comment]
Removing the gnome-keyring package shoud work as well btw.

**Comment by mehturt** [comment]
I removed gnome-keyring and seahorse from my system but still get the same error:
common.keyring.KeyringUnlockException: Failed to unlock default keyring
Regarding the mailnag.config - isn't it supposed to be generated by mailnag-config? If it's a plain text file perhaps I could try to modify it by hand, but looking at Debian mailnag package, there is no example config file bundled.

**Comment by pulb** [comment]
I just noticed jessie has mailnag 1.0. The keyring dependency was removed in mailnag 1.1. So you can try a package from debian unstable, the mailnag ubuntu ppa or download the latest mailnag tarball from github.

Am 30. Juni 2016 11:01:33 MESZ, schrieb mehturt <notifications@github.com>:
>I removed gnome-keyring and seahorse from my system but still get the
>same error:
>common.keyring.KeyringUnlockException: Failed to unlock default keyring
>Regarding the mailnag.config - isn't it supposed to be generated by
>mailnag-config? If it's a plain text file perhaps I could try to modify
>it by hand, but looking at Debian mailnag package, there is no example
>config file bundled.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pulb/mailnag/issues/126#issuecomment-229602971

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mehturt** [comment]
I installed mailnag from testing, which is 1.2.1, but still get the same error.

**Comment by pulb** [comment]
Closing mailnag-config should create the cfg file. Please apply the changes of my first reply to it.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mehturt** [comment]
Here is the complete output:
```
$ mailnag-config 
Traceback (most recent call last):
  File "/usr/bin/mailnag-config", line 61, in <module>
    if __name__ == "__main__":  main()
  File "/usr/bin/mailnag-config", line 44, in main
    confwin = ConfigWindow()
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 100, in __init__
    self._accountman = AccountManager(CredentialStore.from_string(self._cfg.get('core', 'credentialstore')))
  File "/usr/lib/python2.7/dist-packages/Mailnag/common/credentialstore.py", line 75, in from_string
    cs = CredentialStore.get_default()
  File "/usr/lib/python2.7/dist-packages/Mailnag/common/credentialstore.py", line 66, in get_default
    CredentialStore._instance = SupportedCredentialStores[_credentialstoretype]()
  File "/usr/lib/python2.7/dist-packages/Mailnag/common/credentialstore.py", line 96, in __init__
    raise KeyringUnlockException('Failed to unlock default keyring')
Mailnag.common.credentialstore.KeyringUnlockException: Failed to unlock default keyring
```
No config file is generated, at least not in ~/.config/

**Comment by pulb** [comment]
Can you check if the keyring package was installed again?
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mehturt** [comment]
gnome-keyring is not, but some others are:
```
# dpkg -l |grep keyring|grep ^ii | awk '{print $2}'
debian-archive-keyring
gir1.2-gnomekeyring-1.0
libgnome-keyring-common
libgnome-keyring0:amd64
libpam-gnome-keyring
```

**Comment by pulb** [comment]
Its gir1.2-gnomekeyring-1.0.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mehturt** [comment]
Nice, thanks :) Now I see the config GUI :+1:

**Comment by pulb** [comment]
Is everything working now? If so I'll close this issue.

**Comment by mehturt** [comment]
Yes, thanks

**Comment by dschep** [comment]
A note for any one else finding this issue in their searching to fix this, to run `mailnag-config` without having to remove `gir1.2-gnomekeyring-1.0`, just make sure that `~/.config/mailnag/mailnag.cfg` contains:
```
[core]
credentialstore = false
```

(compared to @pulp's comment, note the file name and inclusion of section)
