### ISSUE TITLE
Folder list only lists root folder

### ISSUE THREAD

**Issue by HeikoAdams** [pulb/mailnag#128]
With latest git master the list of folders in config only lists the inbox folder. When running mailnag-config from terminal a lot of 
> WARNING:root:Folder format not supported.

messages are raised.

**Comment by pulb** [comment]
Damn.. and I thought the new regex parsing is bulletproof :grin:
I added debug output for the folder raw format. Can you post the output here?

**Comment by HeikoAdams** [comment]
> $ mailnag-config 
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasChildren) "." "INBOX"
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasChildren) "." "INBOX.Archives"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Archives.2016"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Archives.2015"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Archives.2014"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.DIE LINKE"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasChildren) "." "INBOX.Stellensuche"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Stellensuche.Arbeitsagentur"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Junk E-Mail"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasChildren) "." "INBOX.Soziale Netzwerke"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Soziale Netzwerke.Runtastic"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Soziale Netzwerke.Xing"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Templates"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Trash"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Drafts"
WARNING (2016-08-04 13:44:31): Folder format not supported.
DEBUG (2016-08-04 13:44:31): Folder raw format: (\HasNoChildren) "." "INBOX.Sent"
WARNING (2016-08-04 13:44:31): Folder format not supported.

**Comment by pulb** [comment]
This commit should fix it. Thanks for testing and reporting!
