### ISSUE TITLE
Getting SSL: UNKNOWN_PROTOCOL error

### ISSUE THREAD

**Issue by billg123** [pulb/mailnag#135]
Running mailnag 1.2.1 on a fresh install of Ubuntu 16.04, I configured my work address with known-good credentials (the work mail is using the RackSpace hosted service. In thunderbird, my server settings look like:

server name: secure.emailsrvr.com
username: my username
Connection security: STARTTLS
Authentication method: Normal password
Port 110

So I set up mailnag using:
Account type: POP3
User: my username
password: my password
server: secure.emailsrvr.com
port: 110

I enabled SSL encryption, and am now wondering if that doesn't include STARTTLS support because when I start mailnag the log returns:

INFO (2016-09-25 22:12:59): Successfully enabled plugin 'libnotifyplugin'.
INFO (2016-09-25 22:12:59): Successfully enabled plugin 'spamfilterplugin'.
INFO (2016-09-25 22:12:59): Successfully enabled plugin 'soundplugin'.
INFO (2016-09-25 22:12:59): Successfully enabled plugin 'dbusplugin'.
INFO (2016-09-25 22:12:59): Checking 1 email account(s).
ERROR (2016-09-25 22:13:00): Failed to connect to account 'WireSpring' ([SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)).

Any suggestions?

**Comment by pulb** [comment]
You have to disable SSL in Mailnag (SSL != STARTTLS). If SSL is disabled, Mailnag first tries STARTTLS and if this fails falls back to an unencrypted connection (you get a WARNING in the terminal if this is the case).

**Comment by pulb** [comment]
Oh wait.. You're using POP3. STARTTLS is currently not implemented for POP3. Does your account support IMAP?

**Comment by billg123** [comment]
Unfortunately switching to IMAP would break my workflow with this particular mail account. Guess it's back to the drawing board...

**Comment by pulb** [comment]
Why would it break your workflow? Mailnag does not mark your mails as read if this is what you're concerned about.

**Comment by billg123** [comment]
Yup, I had just realized that after posting. Testing now, and hopefully that will solve my problem. Thanks for the help!

**Comment by pulb** [comment]
Is everything working for you now?
