### ISSUE TITLE
Mailnag exceeds daily gmail limits?

### ISSUE THREAD

**Issue by totalrisp** [pulb/mailnag#142]
Lately google server has been informing me that I am exceeding my daily limits. I am using Gnome 3.22.1 with mailnag. I don't know how to trouble shoot this but I am beginning to suspect that perhaps mailnag is requesting to look at new mails too often. Can this be? I looked at mailnag-config but there does not appear to be any setting that adjusts how often mailnag tries to do what it tries to do.

**Comment by pulb** [comment]
If you configured your email account to use IMAP IDLE (`idle=1` in mailnag.cfg), Mailnag does not check for mail, it recieves a push notification from the gmail server whenever a new mail arrives. If you disabled IMAP IDLE, Mailnag checks for mail depending on the `poll_interval` setting (minutes) specified in mailnag.cfg.

**Comment by totalrisp** [comment]
Ok. Then I guess Mail Nag us not causing this. It seems to be that there are some bugs filed against this version of gnome-online-accounts where it tries to make too many connection requests with google with an expired certificate. So perhaps that is where this is comming from. Sorry about the confusion.
