### ISSUE TITLE
mailnag frequently wakes up which prevents the CPU from their sleep states

### ISSUE THREAD

**Issue by knurd** [pulb/mailnag#143]
While running powertop I noticed that mailnag on my otherwise idle system is responsible for about 50% of the wakeups. It seems to wake the CPU up about 108 times per second here, which is results in unnecessary power consumption.

In case it's relevant: I let mailnag check four folders on two different imap servers and IMAP idle is used afaics.

**Comment by pulb** [comment]
Hey knurd, nice to hear you're still using this awesome piece of software :grin: 
If your accounts have more than one folder enabled, Mailnag currently falls back to polling. IDLE for multiple folders is on top of my TODO list. Nevertheless, 108 wakeups per second is a very high rate and off top of my head I don't know what may be responsible for this. Definitely worth tracking down.

**Comment by pulb** [comment]
Can you check if enabling just one account with one folder reduces the number of wakeups?

**Comment by knurd** [comment]
> nice to hear you're still using this awesome piece of software :grin:
I'm quite happy with it, it does just what I need. Just feel a bit ashamed that I can't find the time and energy to get the related stuff into Fedora :-/

> Can you check if enabling just one account with one folder reduces the number of wakeups?

One account, one folder= 20 Wakeups
Two accounts, each one folder=40 Wakeups
One account, two folders= 68 Wakeups
Two accounts, two folders=108 Wakeups

**Comment by ThibG** [comment]
Hi, I'm also affected by this bug. With 3 accounts, mailnag wakes the CPU 90 to 110 times per second, while with each account individually enabled, it wakes up the CPU about 20 times per second.

Through strace, it seems that the bulk of system calls for individual accounts are:
> [pid  9448] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=50000}) = 0 (Timeout)

When multiple accounts are enabled, additional system calls happen:
> [pid  9608] futex(0x55e7efc2ad30, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
> [pid  9605] futex(0x55e7efc2ad30, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
> [pid  9602] futex(0x55e7efc2ad30, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
> [pid  9605] <... futex resumed> )       = 0
> [pid  9602] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
> [pid  9605] futex(0x55e7efc2ad30, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
> [pid  9602] futex(0x55e7efc2ad30, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
> [pid  9605] <... futex resumed> )       = 1
> [pid  9602] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
> [pid  9605] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=50000} <unfinished ...>
> [pid  9602] futex(0x55e7efc2ad30, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
> [pid  9608] <... futex resumed> )       = 0

Haven't dug further yet.

**Comment by pulb** [comment]
@ThibG many thanks for sharing this insightful information!

**Comment by knurd** [comment]
> So maybe this issue can be closed?

Did a quick look and looks like the python3 port fixed this

**Comment by pulb** [comment]
Great! Thank you guys! :)
