### ISSUE TITLE
Mailnag stopped working after update

### ISSUE THREAD

**Issue by niC00L** [pulb/mailnag#161]
Hi, 
I had mailnag for a long time for both of my gmail accounts. I had no problem with it. After updating to Fedora 26 it stopped working. After examining journalctl I found out this error for both of my accounts:
`([AUTHENTICATIONFAILED] Invalid credentials (Failure)).
`
I'm pretty sure my credentials are correct, because I didn't change them. I didn't change anything. How can I fix this?

**Comment by pulb** [comment]
Maybe [this](https://productforums.google.com/forum/#!topic/apps/6SOFxcccWN4;context-place=topicsearchin/apps/authorid$3AAPn2wQe5SwCwJJ00Zu5NOLpuDgH4_kP0lsGqa8AgY5FaltpTfZ9bamkU6GhxH4aeswAH1cPpgocO%7Csort:date%7Cspell:false) helps? Or [this](https://github.com/pulb/mailnag/issues/112)?

**Comment by niC00L** [comment]
I have 2-step verification, so I created new special app password and it fixed the problem. No idea why the original one didn't work.
