### ISSUE TITLE
add support for kde

### ISSUE THREAD

**Issue by alekksander** [pulb/mailnag#164]
this is really nice program, i can't find any alternative to it, but would it be possible to add support to kde's plasma? tray icon is not working. beside that, all looks good.

**Comment by pizzadude** [comment]
yes, please

**Comment by doronbehar** [comment]
This sounds like a goal for a separate project which should be noted among other desktop integration project listed in the README [here](https://github.com/pulb/mailnag#desktop-integration).

**Comment by alekksander** [comment]
is there anything going on regarding this? kde is missing icon. it's the most important issue, latter on is integration with kwallet and we are all set.

**Comment by DamianBulldog** [comment]
Yes,i want Plasma 5 desktop integration please !

**Comment by IbanRothschild** [comment]
Me too!

**Comment by alekksander** [comment]
@pulb could You please shed some light on this request?
Thank You

**Comment by pulb** [comment]
@alekksander: I don't know if anyone is working on it. For anyone interested in it, the [messaging menu plugin](https://github.com/pulb/mailnag-messagingmenu-plugin) that integrates Mailnag in any taskbar indicator that implements the messaging menu API (as seen in Ubuntu's legacy Unity desktop) should be a good starting point. It's only ~200 lines of code. Maybe it even works out of the box in kde?

**Comment by VladimirMikulic** [comment]
The real question here is, does anyone knows Plasma scripting/widget programming?
I am on my holidays, I am a full-stack web developer, but I am willing to learn Plasma scripting.
Maybe I could start a separate project for Mailnag on KDE.

Some people have already suggested me doing that https://www.reddit.com/r/kde/comments/bzff92/i_am_going_to_build_a_kde_widget_suggestions/

What do you guys think about this?

**Comment by alekksander** [comment]
there is a light at the end of a tunnel:
https://old.reddit.com/r/kde/comments/fl9y9k/is_someone_skilled_enough_to_develop_mailnag/g3u5a4t/

**Comment by Driglu4it** [comment]
> there is a light at the end of a tunnel:
> https://old.reddit.com/r/kde/comments/fl9y9k/is_someone_skilled_enough_to_develop_mailnag/g3u5a4t/

First release: https://store.kde.org/p/1420222/ )))

**Comment by pizzadude** [comment]
Thanks @Driglu4it

**Comment by Driglu4it** [comment]
![Screenshot_20200909_161834](https://user-images.githubusercontent.com/26646214/92603596-295bae80-f2b8-11ea-91cf-89888fc571b3.png)

**Comment by alekksander** [comment]
@Driglu4it do You plan to open dedicated repo soon?

**Comment by Driglu4it** [comment]
Good day. Perhaps a little later.

**Comment by Mailaender** [comment]
I would like to help translate it. Couldn't find the repository.
