### ISSUE TITLE
1.3.0 isn't in Ubuntu 19.04 (disco) and PPA build for extension is broken

### ISSUE THREAD

**Issue by ronjouch** [pulb/mailnag#184]
I'd like to install `mailnag` and `gnome-shell-mailnag` to an Ubuntu 19.04 (disco) box using deb packages, but:

- The version in the repos is 1.2.0, which doesn't work for the Gnome version (3.32) used by this Ubuntu.
- The [PPA build is partially failed](https://launchpad.net/~pulb/+archive/ubuntu/mailnag/+packages?field.name_filter=&field.status_filter=published&field.series_filter=disco) (core built, but extension failed).

I guess 1.3.0 will never arrive in Disco, due to Ubuntu merging policy.

→ Can the PPA build for `gnome-shell-mailnag` be fixed?

Thanks for mailnag 🙂

**Comment by meoxtma** [comment]
Hey guys,
today i installed mailnag from disco 19.04 - PPA.. its Version 1.3.0
http://ppa.launchpad.net/pulb/mailnag/ubuntu disco/main amd64 mailnag all 1.3.0-0~ubuntu19.04.1

But mailnag-config won run
`mailnag-config
  File "/usr/bin/mailnag-config", line 76
    print "Launching Mailnag daemon."
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Launching Mailnag daemon.")?
`
My Python is set to 3.7.3
what can i do ?
gnome-shell-mailnag will not work to. :-(((
Thanks for help..

**Comment by pulb** [comment]
@meoxtma: mailnag (still) requires python 2

@ronjouch: I uploaded a new gnome-shell-mailnag build to the ppa.
