### ISSUE TITLE
User script

### ISSUE THREAD

**Issue by JosephHenley** [pulb/mailnag#194]
Hi,
Can you tell me where to find some info on what the info passed to the user script looks like.  I'd like to write a script using it.  Thanks!
Joe Henley

**Comment by pulb** [comment]
Hi,
as the plugin decription says, mailnag passes the mail count to the script, followed by accountname, sender and subject for every mail. Example:
`scriptname.sh 1 GmailAccount1 abc@example.net News`

Hope this helps.
