### ISSUE TITLE
Mailnag missing from Ubuntu 19.10 Repo

### ISSUE THREAD

**Issue by gitsnow** [pulb/mailnag#201]
Hi,

I recently upgraded to Ubuntu 19.10 and it appears that the 19.10 version of mailnag 1.3.0 is missing from the repository.

**Comment by pulb** [comment]
That's probably because the current mailnag release still requires python2, which is currently being dropped from distros. The upcoming mailnag 2.0 release will require python3 and probably included again in ubuntu repos.
