### ISSUE TITLE
support local mail boxes:mbox and maildir

### ISSUE THREAD

**Issue by ildar** [pulb/mailnag#21]
FR

**Comment by tikank** [comment]
I have also local mail boxes and i like to have Mailnag to support them. I made some tests with Pythons mailbox module, and I think it can be used for this. I might try to make something.

I have not read all of the Mailnag sources yet, but I have some thoughts.

Configuration needs some kind of type field. Now there is only imap, which tells that account is imap or pop (= not imap). I propose field type=imap/pop/mbox/maildir, and to support old configs, if type is not specified, then "type=imap if imap else pop".
mbox and maildir needs also path to the configuration. For mbox it is mbox file, for maildir it is the directory. These don't need user, password, server and port. Maildir can have folders but mbox does not have.

I have not yet looked configuration dialog.

There is now imap and pop related code at least in MailnagDaemon, MailCollector and Account classes. These are the potential places to be modified for mbox and maildir support. Maybe to code should be moved to "account backend" classes, which all have common interface. There could be ImapBackend which contains all imap related code, etc. Then it could be easier to add MboxBackend and MaildirBackend.

Pythons mailbox module does not have notifications for changes, so mailboxes should be polled. That would be ok, but maybe inotify can be used to get notification for mbox file and maildir directory changes. 

Does this sound reasonable? What other things should be considered?

**Comment by tikank** [comment]
I started this by moving IMAP and POP3 code to backend classes, because without that it would be difficult to implement local box support.

I pushed the changes to my clone, but it is not yet ready for pull request. Now it seems that backend interface will contain methods open, close, list_message and request_folders. Some more is needed to support operations in Idlers.py and mailnagdaemon.py.

**Comment by pulb** [comment]
All of this sounds **very** reasonable :-)
Mailnag was forked from [Popper](https://launchpad.net/popper) and extended with new features over the last few years. So some code really needs some refactoring love and some is more ore less in its original spaghetti state (see e.g. mails.py ;).

So your work is highly appreciated and mbox/maildir support is a valuable addition.
Keep up your efforts and keep me posted! :grinning:

**Comment by tikank** [comment]
Progress :-) I made pull request https://github.com/pulb/mailnag/pull/132 which contains move of IMAP and POP3 code to backends. Idlers.py was the trickiest part. I had to look it again when/if local mailboxes support notifications. Please review and tell if something should be changed.

I think next thing would be add type field to configuration so that configuration is not limited to IMAP and not-IMAP. I also try to make some kind of factory for backends.

**Comment by tikank** [comment]
So, now there is pull request https://github.com/pulb/mailnag/pull/134.

Next I will implement maildir. And after that configuration dialog and notifications (not necessary in this order) and finally some cleanup.

**Comment by tikank** [comment]
Pull-request https://github.com/pulb/mailnag/pull/141 adds configuration user interface for MBox and Maildir to account dialog. 

It think that local mailbox support is now at least partially ready. it is not perfect but it is usable. I have used Mailnag a while with two imap accounts, one gmail account, two mboxes and one maildir (maildir is just for testing and some times I have switched one imap to pop3 to test that also). 

Local accounts are polled so they update slowly. This could be made better with inotify. There seems to be some Python libraries for inotify. Does anybody has some preferences which one should or could be used?
* https://pypi.python.org/pypi/pyinotify/0.9.6
* https://pypi.python.org/pypi/pyinotify-smarkets/1.0.0 (a fork from the previous)
* https://pypi.python.org/pypi/inotify/0.2.8
* https://launchpad.net/inotifyx

Pyinotify and inotifyx seem to have debian packages: https://tracker.debian.org/pkg/pyinotify and https://tracker.debian.org/pkg/inotifyx .

**Comment by pulb** [comment]
I guess pyinotify is the way to go, it's available in Arch Linux as well.

**Comment by doronbehar** [comment]
I'm really looking forward to maildir support for mailnag. Is this issue still open just because of the pending enhancement of using a library like `pyinotify`?

**Comment by tikank** [comment]
Yes, I think that is so. 

Mbox and maildir implementation is in master branch and I think it works and is already usable although it is using polling.

**Comment by draxil** [comment]
Did this ever make it into a release? Current ubuntu version doesn't seem to have it?

**Comment by draxil** [comment]
> Did this ever make it into a release? Current ubuntu version doesn't seem to have it?

Ignore me I've found the PPA now :)
