### ISSUE TITLE
Design a new flyer

### ISSUE THREAD

**Issue by pulb** [pulb/mailnag#64]
The current flyer (screenshot image) linked in README.md contains outdated images. The new flyer should show images of the config dialog and the GNOME-Shell / Unity extensions.

This is the current flyer:
![Screenshot](http://www.shockshit.net/mailnag/screenshots/mailnag_flyer.png)

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289149/e975e232-4366-11e5-9048-4ba10f32080a.jpg)
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
