### ISSUE TITLE
Please create an AppData file for Mailnag Configuration

### ISSUE THREAD

**Issue by hughsie** [pulb/mailnag#73]
Please consider writing and installing an AppData file with the application description and some screenshots, else Mailnag Configuration looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by pulb** [comment]
Fixed in Mailnag 1.1.
