### ISSUE TITLE
Create a Cinnamon indicator extension

### ISSUE THREAD

**Issue by pulb** [pulb/mailnag#75]
As the title says. A permanently visible taskbar indicator for Cinnamon (Linux Mint) would be nice. Contributors wanted :)

**Comment by hyOzd** [comment]
Hi, I'm currently working on a Cinnamon applet for mailnag. I thought you would be interested.

https://bitbucket.org/hyOzd/mailnagapplet

Here is how it looks at the moment:
![mailnag_applet](https://cloud.githubusercontent.com/assets/1479166/11325170/87deaf36-914f-11e5-86fd-0b629eb2d71a.png)

It's still work in progress. It's functional though. You get notifications when new mail arrive and you can click the mail icon next to subject line to mark it read. Also shows the number of mails next to the icon.

**Comment by pulb** [comment]
Wow, this is awesome news! Please keep me posted. :grinning:
I already added a link to your repo to README.md.

**Comment by hyOzd** [comment]
Will do so, thanks for the link :)

**Comment by hyOzd** [comment]
I've just released the applet via [cinnamon-spices page](http://cinnamon-spices.linuxmint.com/applets/view/244) . It can be installed from the "Applets" settings.

It looks better now:

![screenshot](https://bytebucket.org/hyOzd/mailnagapplet/raw/df4e2c67f874983b178e30f3a8cc2a7d13cd7719/img/mailnag_menu.png)

But still no avatars. Maybe in the future.

@pulb I was wondering is there way to now which account has received an e-mail. D-Bus "GetMails" method doesn't provide this information. Am I missing something. My mailnag version is `1.1.0`.

**Comment by pulb** [comment]
Looks really awesome! Yes, retrieving avatars is a little bit tricky since you can't use libfolks in js directly. You can just copy over my avatar code if you want, though :smile: 

Account information is currently not exposed by the dbus API. There's already [another request](https://github.com/pulb/mailnag/issues/84) for that but I didn't add it yet because I don't want to break the API yet.

**Comment by hyOzd** [comment]
Hmm, I didn't know about libfolks. I was planning to use gravatar's web API via soup library which has gjs bindings. But I'm guessing using libfolks will give more options other than gravatar..?

**Comment by pulb** [comment]
Yes, libfolks aggregates contact information including avatars from multiple sources (e.g. gnome-contacts, evolution address books, social media sites etc).

**Comment by hyOzd** [comment]
WIP account grouping:

![screenshot from 2016-01-03 23 15 25](https://cloud.githubusercontent.com/assets/1479166/12080812/3a0e22ae-b270-11e5-81a4-911b18241fb8.png)

**Comment by pulb** [comment]
Looks good, I like your idea with the submenus :)

**Comment by pulb** [comment]
Hey, we're [featured on webupd8](http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html)! :grin:

**Comment by hyOzd** [comment]
That's awesome! :D Finally I'm famous!
