### ISSUE TITLE
ElementaryOS support

### ISSUE THREAD

**Issue by trofimchyk** [pulb/mailnag#76]
Hi. Will it work with Elementary OS Luna?

**Comment by trofimchyk** [comment]
Works good in Elementary OS Freya

**Comment by keevitaja** [comment]
But there is no app indicator for the Elementary OS Freya... I just get the notification bubbles and thats it.

**Comment by pulb** [comment]
@keevitaja: Did you install the mailnag-unity-plugin?

**Comment by keevitaja** [comment]
No, i figured it is Unity specific. 

But not i have it installed, rebooted my machine, and still nothing. Only bubble notifications.

**Comment by pulb** [comment]
Did you enable the plugin in mailnag-config?

**Comment by keevitaja** [comment]
No :(

Thank you, it is working perfectly as expected!

**Comment by pulb** [comment]
You're welcome :-)

**Comment by trofimchyk** [comment]
Hi. What about Ubuntu 15.04? I've got sound notification, my email appeared in message indicator, but there was no bubble notification.

**Comment by pulb** [comment]
You have to enable the libnotify plugin. If you upgraded from 14.04. try to reinstall both, mailnag and the unity-plugin.

**Comment by trofimchyk** [comment]
@pulb I did clean install of Ubuntu 15.04. Reinstall mailnag with plugins doesn't work for me.

**Comment by pulb** [comment]
Please run mailnag in a terminal and post the output here.

**Comment by trofimchyk** [comment]
@pulb 
`Shutting down existing Mailnag process...OK`
`INFO (2015-04-30 12:08:15): Successfully enabled plugin 'unityplugin'.`
`INFO (2015-04-30 12:08:15): Successfully enabled plugin 'libnotifyplugin'.`
`INFO (2015-04-30 12:08:15): Successfully enabled plugin 'soundplugin'.`
`INFO (2015-04-30 12:08:15): Successfully enabled plugin 'dbusplugin'.`
`INFO (2015-04-30 12:08:15): Checking 1 email account(s).`

**Comment by pulb** [comment]
Looks ok. Please try to change the notification mode in the libnotify plugin.

**Comment by trofimchyk** [comment]
@pulb I've tried all of them but notification doesn't work. I will try to install Ubuntu on another hardware and check mailnag on it.

**Comment by pulb** [comment]
@trofimchyk: you could also try if libnotify is working on your system by issuing `notify-send "test"` in a terminal.

**Comment by trofimchyk** [comment]
@pulb I've checked on another machine with 15.04. Notifications became working only after I've changed notification mode several times. Anyway thank you for your support!
