### ISSUE TITLE
Add an abstraction layer for credential storage

### ISSUE THREAD

**Issue by pulb** [pulb/mailnag#82]
As  of version 1.0 Mailnag is meant to be desktop independent. However, it still depends on gnome-keyring to store account passwords. 

The codebase should be refactored so that Mailnag never accesses a desktop-specific credential dependency directly. Instead it should access an abstraction layer/interface (_CredentialStore_) which is implemented by desktop-specific backends. Initially there should be two _CredentialStore_ implementations:
* _GnomeCredentialStore_: Backend for GNOME keyring password storage
* _GenericCredentialStore_: Backend for password storage on all other desktops (textfile)

Later on further CredentialStores may be added, e. g. a _KDECredentialStore_.
This should also solve issue #79.

**Comment by Paviluf** [comment]
We really need that Mailnag be desktop independent !

**Comment by pulb** [comment]
FYI this is currently work in progress.

**Comment by Paviluf** [comment]
Great, thank you !
