### ISSUE TITLE
Failed to enable plugin libnotifyplugin

### ISSUE THREAD

**Issue by akovia** [pulb/mailnag#90]
Running Arch + XFCE
Used `sudo aura -A mailnag` and not `yaourt -S mailnag` or `packer -S mailnag` if that makes a difference.

```
INFO (2014-12-19 19:18:01): Successfully enabled plugin 'dbusplugin'.
INFO (2014-12-19 19:18:01): Successfully enabled plugin 'soundplugin'.
ERROR (2014-12-19 19:18:01): Failed to enable plugin 'libnotifyplugin'.
```

This is a fresh install and didn't have any old config files. Not sure how to troubleshoot this.
Thanks.

**Comment by tristan-k** [comment]
+1

**Comment by pulb** [comment]
Just for the record, as of release 1.0 Mailnag does not depend on gnome libs anymore. Someone also created a [Cinnamon applet](https://github.com/pulb/mailnag/issues/75), so creating something similar for XFCE shouldn't be too hard. Maybe you can ask for help/post a request in an appropriate social media community?
