### ISSUE TITLE
No module named xdg.BaseDirectory

### ISSUE THREAD

**Issue by auipga** [pulb/mailnag#91]
After installing from git I get error messages when running mailnag or mailnag-config.
```
➜  ~  mailnag-config 
Traceback (most recent call last):
  File "/usr/sbin/mailnag-config", line 30, in <module>
    from Mailnag.common.utils import set_procname, shutdown_existing_instance, fix_cwd
  File "/usr/lib/python2.7/site-packages/Mailnag/common/utils.py", line 25, in <module>
    import xdg.BaseDirectory as base
ImportError: No module named xdg.BaseDirectory
```
It is a fresh install of arch linux. So I don't know what i did wrong.

**Comment by auipga** [comment]
I missed to install `pyxdg`.

**Comment by pulb** [comment]
There are also [packages in AUR](https://aur.archlinux.org/packages/?O=0&C=0&SeB=nd&K=mailnag&outdated=&SB=n&SO=a&PP=50&do_Search=Go). I will update them as soon as 1.1 is released (within the next few weeks I guess).

**Comment by auipga** [comment]
would be cool to see a mailnag-git version too.
I mentioned that installing mailnag from git and installing mailnag-gnome-shell from AUR will not recognize mailnag. :(

**Comment by pulb** [comment]
You're in luck, someone created [git packages](https://aur.archlinux.org/packages/?O=0&C=0&SeB=nd&K=mailnag&outdated=&SB=n&SO=a&PP=50&do_Search=Go) :-)
