### ISSUE TITLE
Gmail maintains "new email" notification until message is archived

### ISSUE THREAD

**Issue by dagavi** [pulb/mailnag#95]
Hi,
Mailnag shows to me correctly the new emails that I received in my Gmail account, but the problem is that the unread/new email counter remains in 1 (if 1 email is received) and the notification in Ubuntu until I archive the received email.

I can mark as read or open the email that the program remains indicating that I have 1 email (and the mail icon, in Ubuntu, remains in blue). When I archive that email the counter goes to 0 and the notification dissapears.

My expected behaviour is that the notification/email counter only shows unread emails, not only new emails not archived.

**Comment by pulb** [comment]
This is indeed unexpected behaviour. Is there something special with your email account, e.g. did you configure any filters or similar? Did you specify any folder names in mailnag-config?

**Comment by dagavi** [comment]
I have lot of filters, but no one is processing these emails (only automatic classification from gmail that labels this email as "Notification"). I have no configuration in "folder" section of gmail-mailnag.

I did a new test: I received a email -> notification is received and email counter = 1.
I went to Gmail web interface and read the email.
After 8 minutes the email counter remains in 1 and the Ubuntu notificacion in blue color.
I opened Mailnag configuration and entered in accounts -> [my account] -> edit to answer the Folder question. When I clossed this window the notification dissapeared.

I tryed again:
Received email -> instant notification -> Open mailnag gmail configuration and closed the windows (notification remails) -> A NEW NOTIFICACION IS RECEIVED (seems that the program reloads the configuration and re-checks the emails) -> Open again mailnag (withouth enter in Gmail config) and close -> new noification -> I read the email -> no change -> open and close mailnag configuration window -> notification is gone.

I test a last time only receiving the email reading and clicking on "archive". Just after click on "archive" the notification is gone.

**Comment by pulb** [comment]
Can you please post the contents of ~/.config/mailnag/mailnag.cfg?

**Comment by dagavi** [comment]
[spamfilterplugin]
filter_text = newsletter, viagra

[core]
imap_idle_timeout = 10
enabled_plugins = dbusplugin, libnotifyplugin, unityplugin
poll_interval = 10
credentialstore = auto
connectivity_test = auto
autostart = 1

[unityplugin]
max_visible_mails = 10

[soundplugin]
soundfile = mailnag.ogg

[libnotifyplugin]
notification_mode = 1
max_visible_mails = 10

[account1]
enabled = 1
name = USERNAME (Gmail)
user = USERNAME
password = 
server = imap.gmail.com
port = 993
ssl = 1
imap = 1
idle = 1
folder = 

[userscriptplugin]
script_file =

**Comment by dagavi** [comment]
I saw these lines in this configuration:
imap_idle_timeout = 10
poll_interval = 10

And I suposed that are values in minutes. After 10 minutes of reveiving the notification of your answer/request the notification has gone without archive the email (only reading it). ¿Is normal that IMAP doesn't notificates that an email is readed and only notificates new or deleted/archived messages?

**Comment by pulb** [comment]
Ok, I can reproduce that behaviour. Something is wrong. I'll look into it.

**Comment by pulb** [comment]
According to [this](https://productforums.google.com/forum/#!topic/gmail/XAZxaJRed0o) and [this](https://code.google.com/p/k9mail/issues/detail?id=2160#c15) post, GMail only sends push  notifications for 'DELETE' and 'NEW MAIL' events. It does not send notifications for tag events (like setting the 'READ' tag). So unfortunately there's nothing I can do :-\

P.S.: `poll_interval` is only used by polling connections (i.e. POP3 and Non-Push IMAP accounts). `imap_idle_timeout` is used by IMAP Push accounts like yours. It specifies the timeout in minutes, after which Mailnag will pull changes from a mail server if there were no push notifications. So as a workaround you can set this timeout to something smaller. I.e. if you set it to 3, Mailnag will remove read mails after 3 minutes at the latest.

**Comment by dagavi** [comment]
:( Ok no problem. I archive all my mail.

**Comment by pulb** [comment]
As an alternative solution to the imap_idle_timeout workaround, you could also use an email client that downloads received mail (like Evolution or Thunderbird).
