### ISSUE TITLE
Feature request: add support for STARTTLS

### ISSUE THREAD

**Issue by bagage** [pulb/mailnag#99]
I am not sure 100% about that, but can you confirm that mailnag does not support STARTTLS connectivity yet? If so, it would be great to have it as an alternative to secure SSL.
Currently on master version, I am getting errno 101: network unreachable when trying to connect with a secure SSL connection.

**Comment by kaptoxic** [comment]
+1 :+1:
I just get: "Cannot connect to IMAP account" when trying to connect to an account to which I otherwise connect with STARTTLS
